//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MainText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressLine1.
        /// </summary>
        internal static string Address1Label {
            get {
                return ResourceManager.GetString("Address1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressLine2.
        /// </summary>
        internal static string Address2Label {
            get {
                return ResourceManager.GetString("Address2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressLine3.
        /// </summary>
        internal static string Address3Label {
            get {
                return ResourceManager.GetString("Address3Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or higher required.
        /// </summary>
        internal static string AdobeDescLabel {
            get {
                return ResourceManager.GetString("AdobeDescLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrobat Reader 9.
        /// </summary>
        internal static string AdobeHeaderLabel {
            get {
                return ResourceManager.GetString("AdobeHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelbtnText {
            get {
                return ResourceManager.GetString("CancelbtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ClosebtnText {
            get {
                return ResourceManager.GetString("ClosebtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyName.
        /// </summary>
        internal static string CompanyLabel {
            get {
                return ResourceManager.GetString("CompanyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your standard contact details will be included in the brochure - you may modify them now if required..
        /// </summary>
        internal static string ContactDetailsDescText {
            get {
                return ResourceManager.GetString("ContactDetailsDescText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My contact details.
        /// </summary>
        internal static string ContactDetailsLabel {
            get {
                return ResourceManager.GetString("ContactDetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Details.
        /// </summary>
        internal static string ContactdialogTitle {
            get {
                return ResourceManager.GetString("ContactdialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Contact details Updated Successfully!!.
        /// </summary>
        internal static string ContactUpdateSuccessMsg {
            get {
                return ResourceManager.GetString("ContactUpdateSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string CountryLabel {
            get {
                return ResourceManager.GetString("CountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your standard Customize details will be included in their corresponding brochure - you may modify them now if required.
        /// </summary>
        internal static string CustomDetailsDescText {
            get {
                return ResourceManager.GetString("CustomDetailsDescText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize details.
        /// </summary>
        internal static string CustomDetailsLabel {
            get {
                return ResourceManager.GetString("CustomDetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPACT Home.
        /// </summary>
        internal static string IMPACTHome {
            get {
                return ResourceManager.GetString("IMPACTHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My logo.
        /// </summary>
        internal static string LogoLabel {
            get {
                return ResourceManager.GetString("LogoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your standard logo will be included on the brochure. Click &apos;upload&apos; below to change it..
        /// </summary>
        internal static string LogoLabelDescText {
            get {
                return ResourceManager.GetString("LogoLabelDescText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your logo saved successfully !!.
        /// </summary>
        internal static string LogoSaved {
            get {
                return ResourceManager.GetString("LogoSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Max. 800 * 800 pixels, RGB Mode, JPG or PNG.
        /// </summary>
        internal static string LogoSizeDescText {
            get {
                return ResourceManager.GetString("LogoSizeDescText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Logo Updated  Successfully!!.
        /// </summary>
        internal static string LogoUpdateSuccessMsg {
            get {
                return ResourceManager.GetString("LogoUpdateSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been an error in reaching this web page, the system has detected a missing parameter ({0}). You will be redirected back to the Smart Centre site and please try again. If this issue persists, please contact your web administrator..
        /// </summary>
        internal static string MissingQueryStringParamter {
            get {
                return ResourceManager.GetString("MissingQueryStringParamter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactNumber.
        /// </summary>
        internal static string PhoneLabel {
            get {
                return ResourceManager.GetString("PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        internal static string PostcodeLabel {
            get {
                return ResourceManager.GetString("PostcodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof your Document carefully before placing your order..
        /// </summary>
        internal static string ProofDescLabel {
            get {
                return ResourceManager.GetString("ProofDescLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORTANT.
        /// </summary>
        internal static string ProofHeaderLabel {
            get {
                return ResourceManager.GetString("ProofHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SavebtnText {
            get {
                return ResourceManager.GetString("SavebtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select file for upload....
        /// </summary>
        internal static string SelectFileMsg {
            get {
                return ResourceManager.GetString("SelectFileMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMART Centre .
        /// </summary>
        internal static string SmartCentreTitle {
            get {
                return ResourceManager.GetString("SmartCentreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string StateLabel {
            get {
                return ResourceManager.GetString("StateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        internal static string TownLabel {
            get {
                return ResourceManager.GetString("TownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        internal static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdatebtnText {
            get {
                return ResourceManager.GetString("UpdatebtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload.
        /// </summary>
        internal static string UploadbtnText {
            get {
                return ResourceManager.GetString("UploadbtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebUrl.
        /// </summary>
        internal static string UrlLabel {
            get {
                return ResourceManager.GetString("UrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select valid file type....
        /// </summary>
        internal static string ValidFileTypeMsg {
            get {
                return ResourceManager.GetString("ValidFileTypeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Proof.
        /// </summary>
        internal static string ViewPrrofbtnText {
            get {
                return ResourceManager.GetString("ViewPrrofbtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPACT Marketplace - Collateral Creator Tool.
        /// </summary>
        internal static string XeroxTitle {
            get {
                return ResourceManager.GetString("XeroxTitle", resourceCulture);
            }
        }
    }
}
