//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreator.Web.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BuiltDocument_aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BuiltDocument_aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CollateralCreator.Web.App_LocalResources.BuiltDocument.aspx", typeof(BuiltDocument_aspx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back to Collateral Creator.
        /// </summary>
        public static string BackHomebtnText {
            get {
                return ResourceManager.GetString("BackHomebtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are here:.
        /// </summary>
        public static string BreadCrumbText {
            get {
                return ResourceManager.GetString("BreadCrumbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c/o.
        /// </summary>
        public static string EmailCareOf {
            get {
                return ResourceManager.GetString("EmailCareOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xerox Collateral Creator Order Confirmation.
        /// </summary>
        public static string EmailConfirmHeader {
            get {
                return ResourceManager.GetString("EmailConfirmHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies.
        /// </summary>
        public static string EmailCopies {
            get {
                return ResourceManager.GetString("EmailCopies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string EmailDate {
            get {
                return ResourceManager.GetString("EmailDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered to the following address:.
        /// </summary>
        public static string EmailDelivered {
            get {
                return ResourceManager.GetString("EmailDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string EmailFooterAllrights {
            get {
                return ResourceManager.GetString("EmailFooterAllrights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should receive your order within &lt;strong&gt;10 business&lt;/strong&gt; days by &lt;strong&gt;mail&lt;/strong&gt;..
        /// </summary>
        public static string EmailFooterMain {
            get {
                return ResourceManager.GetString("EmailFooterMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For additional assistance please &lt;strong&gt;contact your Xerox Inside Partner Manager.&lt;/strong&gt;.
        /// </summary>
        public static string EmailFooterSub {
            get {
                return ResourceManager.GetString("EmailFooterSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string EmailOrder {
            get {
                return ResourceManager.GetString("EmailOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your order is being processed..
        /// </summary>
        public static string EmailOrderStatment {
            get {
                return ResourceManager.GetString("EmailOrderStatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER SUMMARY.
        /// </summary>
        public static string EmailOrderSummary {
            get {
                return ResourceManager.GetString("EmailOrderSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear.
        /// </summary>
        public static string EmailSalutation {
            get {
                return ResourceManager.GetString("EmailSalutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You for Your Order.
        /// </summary>
        public static string EmailThankYou {
            get {
                return ResourceManager.GetString("EmailThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow up to 2 weeks (10 business days) for delivery of your Document. While delivery to Canada, Puerto Rico and Guam cannot be guaranteed within the two week time frame, best effort will be applied. We will contact you if we have any questions or concerns..
        /// </summary>
        public static string OrderDeliveryText {
            get {
                return ResourceManager.GetString("OrderDeliveryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Built.
        /// </summary>
        public static string OrderHeaderText {
            get {
                return ResourceManager.GetString("OrderHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Thank you for Your Order&lt;/b&gt; - a confirmation email will be sent to you shortly..
        /// </summary>
        public static string OrderThanksText {
            get {
                return ResourceManager.GetString("OrderThanksText", resourceCulture);
            }
        }
    }
}
