//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreator.Web.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Edit_aspx_fi_Fl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Edit_aspx_fi_Fl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CollateralCreator.Web.App_LocalResources.Edit.aspx.fi-Fl", typeof(Edit_aspx_fi_Fl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are here:.
        /// </summary>
        public static string BreadCrumbTxt {
            get {
                return ResourceManager.GetString("BreadCrumbTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to main menu.
        /// </summary>
        public static string btnBacktoMenuText {
            get {
                return ResourceManager.GetString("btnBacktoMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download(PDF).
        /// </summary>
        public static string btnDownloadText {
            get {
                return ResourceManager.GetString("btnDownloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize Preview.
        /// </summary>
        public static string btnMaxPreiewText {
            get {
                return ResourceManager.GetString("btnMaxPreiewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Prints.
        /// </summary>
        public static string btnOrderPrintsText {
            get {
                return ResourceManager.GetString("btnOrderPrintsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Preview.
        /// </summary>
        public static string btnUpdatePreviewText {
            get {
                return ResourceManager.GetString("btnUpdatePreviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change logo.
        /// </summary>
        public static string ChangebtnText {
            get {
                return ResourceManager.GetString("ChangebtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change image.
        /// </summary>
        public static string ChangebtnText1 {
            get {
                return ResourceManager.GetString("ChangebtnText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to go back to Main Menu ?.
        /// </summary>
        public static string ConfirmBackText {
            get {
                return ResourceManager.GetString("ConfirmBackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable text -.
        /// </summary>
        public static string CustomAreaTxt {
            get {
                return ResourceManager.GetString("CustomAreaTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your logo -.
        /// </summary>
        public static string CustomImageTxt {
            get {
                return ResourceManager.GetString("CustomImageTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable Text -.
        /// </summary>
        public static string CustomizeAreaTxt {
            get {
                return ResourceManager.GetString("CustomizeAreaTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Max. 800 * 800 pixels, RGB Mode, JPG or PNG.
        /// </summary>
        public static string CustomizeImgText1 {
            get {
                return ResourceManager.GetString("CustomizeImgText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In page image: &lt;width&gt; x &lt;height&gt; pixels, with 90 px rounded corners, 300 dpi, CMYK colour mode.
        /// </summary>
        public static string CustomizeImgText2 {
            get {
                return ResourceManager.GetString("CustomizeImgText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the fields for your customized document. Press &lt;strong&gt;Update Preview&lt;/strong&gt; to see an updated pdf, press &lt;strong&gt;Maximize Preview&lt;/strong&gt; to open the pdf preview document in a preview window, press &lt;strong&gt;Download&lt;/strong&gt; to download the pdf document or &lt;strong&gt;Order Prints&lt;/strong&gt; to send the document to printshop..
        /// </summary>
        public static string CustomizeMsgText {
            get {
                return ResourceManager.GetString("CustomizeMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Address, Phone, Web URL.
        /// </summary>
        public static string CustomizeMsgText1 {
            get {
                return ResourceManager.GetString("CustomizeMsgText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;
        ///Note: Max. &lt;maxlines&gt; lines, &lt;maxchars&gt; characters per line&quot;.
        /// </summary>
        public static string CustomizeMsgText2 {
            get {
                return ResourceManager.GetString("CustomizeMsgText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Company Name.
        /// </summary>
        public static string CustomizeMsgText3 {
            get {
                return ResourceManager.GetString("CustomizeMsgText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Company Name and Phone Number.
        /// </summary>
        public static string CustomizeMsgText4 {
            get {
                return ResourceManager.GetString("CustomizeMsgText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Phone Number and Web URL.
        /// </summary>
        public static string CustomizeMsgText5 {
            get {
                return ResourceManager.GetString("CustomizeMsgText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters maximum approx.
        /// </summary>
        public static string CustomizeMsgText6 {
            get {
                return ResourceManager.GetString("CustomizeMsgText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string DialogCancelbtnText {
            get {
                return ResourceManager.GetString("DialogCancelbtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload.
        /// </summary>
        public static string DialogUploadbtnText {
            get {
                return ResourceManager.GetString("DialogUploadbtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are customizing.
        /// </summary>
        public static string EditDocumentMsg {
            get {
                return ResourceManager.GetString("EditDocumentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit customized document.
        /// </summary>
        public static string EditHeaderLabel {
            get {
                return ResourceManager.GetString("EditHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line  &lt;linecount&gt; - Max number of characters exceeded..
        /// </summary>
        public static string MaxCharErrorMessage {
            get {
                return ResourceManager.GetString("MaxCharErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max number of lines exceeded in the Editable Text..
        /// </summary>
        public static string MaxLineErrorMessage {
            get {
                return ResourceManager.GetString("MaxLineErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select from the images below and upload.
        /// </summary>
        public static string MultiImageLabel {
            get {
                return ResourceManager.GetString("MultiImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We advise that you edit your &lt;I&gt;Contact Details, Customizable Details and your Company Logo&lt;/i&gt; from the homepage before using this tool. You only need to update these details once..
        /// </summary>
        public static string NoDetailsLabel {
            get {
                return ResourceManager.GetString("NoDetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are preparing your report, please wait....
        /// </summary>
        public static string PreparingReport {
            get {
                return ResourceManager.GetString("PreparingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saving....
        /// </summary>
        public static string SavingTxt {
            get {
                return ResourceManager.GetString("SavingTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the fields for your customized document. Press &lt;strong&gt;Update Preview&lt;/strong&gt; to see an updated pdf, press &lt;strong&gt;Download&lt;/strong&gt; to download the pdf document..
        /// </summary>
        public static string SmartCustomizeMsgText {
            get {
                return ResourceManager.GetString("SmartCustomizeMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We advise that you update your &lt;I&gt;Contact Details, Customizable Details and your Company Logo&lt;/I&gt; from the page before downloading the Collateral..
        /// </summary>
        public static string SmartNoDetailMsgText {
            get {
                return ResourceManager.GetString("SmartNoDetailMsgText", resourceCulture);
            }
        }
    }
}
