//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreator.Web.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home_aspx__fi_Fl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home_aspx__fi_Fl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CollateralCreator.Web.App_LocalResources.Home.aspx..fi-Fl", typeof(Home_aspx__fi_Fl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose branding.
        /// </summary>
        public static string BrandHeaderText {
            get {
                return ResourceManager.GetString("BrandHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are here:.
        /// </summary>
        public static string BreadCrumbTxt {
            get {
                return ResourceManager.GetString("BreadCrumbTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ClosebtnText {
            get {
                return ResourceManager.GetString("ClosebtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorQube 8700.
        /// </summary>
        public static string DefaultProduct {
            get {
                return ResourceManager.GetString("DefaultProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download(PDF).
        /// </summary>
        public static string DownloadbtnText {
            get {
                return ResourceManager.GetString("DownloadbtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditbtnText {
            get {
                return ResourceManager.GetString("EditbtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data exists in DB.
        /// </summary>
        public static string NoDataText {
            get {
                return ResourceManager.GetString("NoDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendation: Please review and update your &lt;i&gt;Contact Details, Customizable Details and your Company Logo&lt;/i&gt; below. These updates will appear on all collateral pieces and only need to be added once..
        /// </summary>
        public static string NoDetailsLabel {
            get {
                return ResourceManager.GetString("NoDetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Prints.
        /// </summary>
        public static string OrderbtnText {
            get {
                return ResourceManager.GetString("OrderbtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner-branded  (Your Company Logo (front pg) + Xerox Authorized Channel Partner Logo).
        /// </summary>
        public static string PartnerBrandText {
            get {
                return ResourceManager.GetString("PartnerBrandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string PreviewbtnText {
            get {
                return ResourceManager.GetString("PreviewbtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show recent Activity.
        /// </summary>
        public static string RecentActivity_Text {
            get {
                return ResourceManager.GetString("RecentActivity.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize and download.
        /// </summary>
        public static string RightpanelHeader_Text {
            get {
                return ResourceManager.GetString("RightpanelHeader.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Selected.
        /// </summary>
        public static string SelectedText_Text {
            get {
                return ResourceManager.GetString("SelectedText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Product, Service or Solution.
        /// </summary>
        public static string SelectProduct_Text {
            get {
                return ResourceManager.GetString("SelectProduct.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create custom-made brochures, flyers, advertisements and direct mail collateral quickly and easily using the Collateral Creator. Your contact details and logo are automatically populated within your document at a click of a button. You can then either download and print your document yourself or notify our preferred print shop to do this for you..
        /// </summary>
        public static string WelcomeDesc_Text {
            get {
                return ResourceManager.GetString("WelcomeDesc.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Collateral Creator.
        /// </summary>
        public static string WelcomeMsg_Text {
            get {
                return ResourceManager.GetString("WelcomeMsg.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xerox branded (Xerox Logo (front pg) + your company logo ).
        /// </summary>
        public static string XeroxBrandText {
            get {
                return ResourceManager.GetString("XeroxBrandText", resourceCulture);
            }
        }
    }
}
