//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreator.Web.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderDocument_aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderDocument_aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CollateralCreator.Web.App_LocalResources.OrderDocument.aspx", typeof(OrderDocument_aspx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an address..
        /// </summary>
        public static string AddressErrorText {
            get {
                return ResourceManager.GetString("AddressErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string AddressLabel {
            get {
                return ResourceManager.GetString("AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a attention text..
        /// </summary>
        public static string AttentionErrorText {
            get {
                return ResourceManager.GetString("AttentionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string AttentionLabel {
            get {
                return ResourceManager.GetString("AttentionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are here:.
        /// </summary>
        public static string BreadCrumbText {
            get {
                return ResourceManager.GetString("BreadCrumbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelbtnText {
            get {
                return ResourceManager.GetString("CancelbtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a city..
        /// </summary>
        public static string CityErrorText {
            get {
                return ResourceManager.GetString("CityErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CityLabel {
            get {
                return ResourceManager.GetString("CityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Correction.
        /// </summary>
        public static string ColorCorrectionLabel {
            get {
                return ResourceManager.GetString("ColorCorrectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial.
        /// </summary>
        public static string ColorCorrectionText {
            get {
                return ResourceManager.GetString("ColorCorrectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the company name..
        /// </summary>
        public static string CompanyErrorText {
            get {
                return ResourceManager.GetString("CompanyErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyNameLabel {
            get {
                return ResourceManager.GetString("CompanyNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Delivery Address&lt;/strong&gt;.
        /// </summary>
        public static string DeliveryAddressLabel {
            get {
                return ResourceManager.GetString("DeliveryAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Method.
        /// </summary>
        public static string DeliveryMethodLabel {
            get {
                return ResourceManager.GetString("DeliveryMethodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an email address..
        /// </summary>
        public static string EmailErrorText {
            get {
                return ResourceManager.GetString("EmailErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a first name..
        /// </summary>
        public static string FirstNameErrorText {
            get {
                return ResourceManager.GetString("FirstNameErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplex.
        /// </summary>
        public static string GeoLabelDuplexText {
            get {
                return ResourceManager.GetString("GeoLabelDuplexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplex.
        /// </summary>
        public static string GeoLabelSimplexText {
            get {
                return ResourceManager.GetString("GeoLabelSimplexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplex vs.Duplex.
        /// </summary>
        public static string GeometryLabel {
            get {
                return ResourceManager.GetString("GeometryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is in the wrong format (e.g. palsmith@email.com)..
        /// </summary>
        public static string InvalidEmailErrorText {
            get {
                return ResourceManager.GetString("InvalidEmailErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a last name..
        /// </summary>
        public static string LastNameErrorText {
            get {
                return ResourceManager.GetString("LastNameErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Order Contact Information&lt;/strong&gt;.
        /// </summary>
        public static string OrderContactLabel {
            get {
                return ResourceManager.GetString("OrderContactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order My Document.
        /// </summary>
        public static string OrderHeaderLabel {
            get {
                return ResourceManager.GetString("OrderHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper Options.
        /// </summary>
        public static string PaperOptionsLabel {
            get {
                return ResourceManager.GetString("PaperOptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper size.
        /// </summary>
        public static string PaperSizeLabel {
            get {
                return ResourceManager.GetString("PaperSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-size (8.5 * 11).
        /// </summary>
        public static string PaperSizeText {
            get {
                return ResourceManager.GetString("PaperSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a contact number..
        /// </summary>
        public static string PhoneErrorText {
            get {
                return ResourceManager.GetString("PhoneErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PhoneLabel {
            get {
                return ResourceManager.GetString("PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a postal code..
        /// </summary>
        public static string PostalCodeErrorText {
            get {
                return ResourceManager.GetString("PostalCodeErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip/Postal Code.
        /// </summary>
        public static string PostalCodeLabel {
            get {
                return ResourceManager.GetString("PostalCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed Collateral.
        /// </summary>
        public static string PrintedCollateralLabel {
            get {
                return ResourceManager.GetString("PrintedCollateralLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print my job using.
        /// </summary>
        public static string PrintJobLabel {
            get {
                return ResourceManager.GetString("PrintJobLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Mode.
        /// </summary>
        public static string PrintModeLabel {
            get {
                return ResourceManager.GetString("PrintModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-Quality.
        /// </summary>
        public static string PrintModeText {
            get {
                return ResourceManager.GetString("PrintModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Choose Print Options&lt;/strong&gt;.
        /// </summary>
        public static string PrintOptionsLabel {
            get {
                return ResourceManager.GetString("PrintOptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print on 100% Recycled Paper..
        /// </summary>
        public static string PrintPaperText {
            get {
                return ResourceManager.GetString("PrintPaperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the quantity..
        /// </summary>
        public static string QuantityErrorText {
            get {
                return ResourceManager.GetString("QuantityErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string QuantityLabel {
            get {
                return ResourceManager.GetString("QuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum quantity 1,000.
        /// </summary>
        public static string QuantityText {
            get {
                return ResourceManager.GetString("QuantityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a state..
        /// </summary>
        public static string StateErrorText {
            get {
                return ResourceManager.GetString("StateErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string StateLabel {
            get {
                return ResourceManager.GetString("StateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitbtnText {
            get {
                return ResourceManager.GetString("SubmitbtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill all the required mandatory fields before placing the order..
        /// </summary>
        public static string ValidationHeaderText {
            get {
                return ResourceManager.GetString("ValidationHeaderText", resourceCulture);
            }
        }
    }
}
