//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreator.Web.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderSummary_aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderSummary_aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CollateralCreator.Web.App_LocalResources.OrderSummary.aspx", typeof(OrderSummary_aspx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are here:.
        /// </summary>
        public static string BreadCrumbText {
            get {
                return ResourceManager.GetString("BreadCrumbText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CancelbtnText {
            get {
                return ResourceManager.GetString("CancelbtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Correction.
        /// </summary>
        public static string ColorCorrectionLabel {
            get {
                return ResourceManager.GetString("ColorCorrectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizable Area.
        /// </summary>
        public static string CustomizeAreaTxt {
            get {
                return ResourceManager.GetString("CustomizeAreaTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplex vs.Duplex.
        /// </summary>
        public static string GeometryLabel {
            get {
                return ResourceManager.GetString("GeometryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper Options.
        /// </summary>
        public static string PaperOptionsLabel {
            get {
                return ResourceManager.GetString("PaperOptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper size.
        /// </summary>
        public static string PaperSizeLabel {
            get {
                return ResourceManager.GetString("PaperSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Logo.
        /// </summary>
        public static string PartnerLogoTxt {
            get {
                return ResourceManager.GetString("PartnerLogoTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print my job using.
        /// </summary>
        public static string PrintJobLabel {
            get {
                return ResourceManager.GetString("PrintJobLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-Quality.
        /// </summary>
        public static string PrintModeText {
            get {
                return ResourceManager.GetString("PrintModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string QuantityLabel {
            get {
                return ResourceManager.GetString("QuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Order.
        /// </summary>
        public static string SubmitOrderbtnText {
            get {
                return ResourceManager.GetString("SubmitOrderbtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Address.
        /// </summary>
        public static string SummaryDeliveryText {
            get {
                return ResourceManager.GetString("SummaryDeliveryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Summary.
        /// </summary>
        public static string SummaryHeaderText {
            get {
                return ResourceManager.GetString("SummaryHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Contact Information.
        /// </summary>
        public static string SummaryOrderContactText {
            get {
                return ResourceManager.GetString("SummaryOrderContactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Options.
        /// </summary>
        public static string SummaryPrintOptionsText {
            get {
                return ResourceManager.GetString("SummaryPrintOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Product.
        /// </summary>
        public static string SummarySelectedProductText {
            get {
                return ResourceManager.GetString("SummarySelectedProductText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review the following for accuracy.
        /// </summary>
        public static string SummarySubheaderText {
            get {
                return ResourceManager.GetString("SummarySubheaderText", resourceCulture);
            }
        }
    }
}
