//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreator.Web.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RecentActivity_aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecentActivity_aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CollateralCreator.Web.App_LocalResources.RecentActivity.aspx", typeof(RecentActivity_aspx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are here:.
        /// </summary>
        public static string BreadCrumbTxt {
            get {
                return ResourceManager.GetString("BreadCrumbTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        public static string ClonebtnText {
            get {
                return ResourceManager.GetString("ClonebtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ClosebtnText {
            get {
                return ResourceManager.GetString("ClosebtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the document?.
        /// </summary>
        public static string ConfirmDeleteText {
            get {
                return ResourceManager.GetString("ConfirmDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new collateral.
        /// </summary>
        public static string CreateCollateralText {
            get {
                return ResourceManager.GetString("CreateCollateralText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteBtnText {
            get {
                return ResourceManager.GetString("DeleteBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditbtnText {
            get {
                return ResourceManager.GetString("EditbtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gone to print.
        /// </summary>
        public static string GoneToprntText {
            get {
                return ResourceManager.GetString("GoneToprntText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the last week.
        /// </summary>
        public static string LastweekHeaderText {
            get {
                return ResourceManager.GetString("LastweekHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendation: Please review and update your &lt;i&gt;Contact Details, Customizable Details and your Company Logo&lt;/i&gt; below. These updates will appear on all collateral pieces and only need to be added once..
        /// </summary>
        public static string NoDetailsLabel {
            get {
                return ResourceManager.GetString("NoDetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner-branded (Xerox Authorized Channel Partner).
        /// </summary>
        public static string PartnerBrandText {
            get {
                return ResourceManager.GetString("PartnerBrandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older.
        /// </summary>
        public static string PreviousHeaderText {
            get {
                return ResourceManager.GetString("PreviousHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My print house activity.
        /// </summary>
        public static string PrintHouseText {
            get {
                return ResourceManager.GetString("PrintHouseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My recent activity.
        /// </summary>
        public static string RecentActivityText {
            get {
                return ResourceManager.GetString("RecentActivityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Activity.
        /// </summary>
        public static string RecentText {
            get {
                return ResourceManager.GetString("RecentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        public static string ShowAllText {
            get {
                return ResourceManager.GetString("ShowAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show less.
        /// </summary>
        public static string ShowLessText {
            get {
                return ResourceManager.GetString("ShowLessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string TodayHeaderText {
            get {
                return ResourceManager.GetString("TodayHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ViewbtnText {
            get {
                return ResourceManager.GetString("ViewbtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xerox branded.
        /// </summary>
        public static string XeroxBrandText {
            get {
                return ResourceManager.GetString("XeroxBrandText", resourceCulture);
            }
        }
    }
}
