//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Menu", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string MenuTree {
            get {
                return ResourceManager.GetString("MenuTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochure.
        /// </summary>
        internal static string MenuTreeBrochure {
            get {
                return ResourceManager.GetString("MenuTreeBrochure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Up &amp; Cash In.
        /// </summary>
        internal static string MenuTreeCleanUpCashIn {
            get {
                return ResourceManager.GetString("MenuTreeCleanUpCashIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Massive savings .
        /// </summary>
        internal static string MenuTreeCleanUpCashIneConcierge {
            get {
                return ResourceManager.GetString("MenuTreeCleanUpCashIneConcierge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best -ever savings.
        /// </summary>
        internal static string MenuTreeCleanUpCashInMPS {
            get {
                return ResourceManager.GetString("MenuTreeCleanUpCashInMPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time flies.
        /// </summary>
        internal static string MenuTreeCleanUpCashInProduct {
            get {
                return ResourceManager.GetString("MenuTreeCleanUpCashInProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorQube 8700.
        /// </summary>
        internal static string MenuTreeColorQube8700 {
            get {
                return ResourceManager.GetString("MenuTreeColorQube8700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochure.
        /// </summary>
        internal static string MenuTreeColorQube8700Brochure {
            get {
                return ResourceManager.GetString("MenuTreeColorQube8700Brochure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectMail.
        /// </summary>
        internal static string MenuTreeColorQube8700DM {
            get {
                return ResourceManager.GetString("MenuTreeColorQube8700DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string MenuTreeColorQube8700Flyer {
            get {
                return ResourceManager.GetString("MenuTreeColorQube8700Flyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorQube 8900.
        /// </summary>
        internal static string MenuTreeColorQube8900 {
            get {
                return ResourceManager.GetString("MenuTreeColorQube8900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochure.
        /// </summary>
        internal static string MenuTreeColorQube8900Brochure {
            get {
                return ResourceManager.GetString("MenuTreeColorQube8900Brochure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectMail.
        /// </summary>
        internal static string MenuTreeColorQube8900DM {
            get {
                return ResourceManager.GetString("MenuTreeColorQube8900DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string MenuTreeColorQube8900Flyer {
            get {
                return ResourceManager.GetString("MenuTreeColorQube8900Flyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorQube 9301/9303.
        /// </summary>
        internal static string MenuTreeColorQube9301_03 {
            get {
                return ResourceManager.GetString("MenuTreeColorQube9301-03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochure.
        /// </summary>
        internal static string MenuTreeColorQube9301_03Brochure {
            get {
                return ResourceManager.GetString("MenuTreeColorQube9301-03Brochure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectMail.
        /// </summary>
        internal static string MenuTreeColorQube9301_03DM {
            get {
                return ResourceManager.GetString("MenuTreeColorQube9301-03DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string MenuTreeColorQube9301_03Flyer {
            get {
                return ResourceManager.GetString("MenuTreeColorQube9301-03Flyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectKey.
        /// </summary>
        internal static string MenuTreeConnectKey {
            get {
                return ResourceManager.GetString("MenuTreeConnectKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochure.
        /// </summary>
        internal static string MenuTreeConnectKeyBrochure {
            get {
                return ResourceManager.GetString("MenuTreeConnectKeyBrochure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectMail.
        /// </summary>
        internal static string MenuTreeConnectKeyDM {
            get {
                return ResourceManager.GetString("MenuTreeConnectKeyDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string MenuTreeConnectKeyFlyer {
            get {
                return ResourceManager.GetString("MenuTreeConnectKeyFlyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkCentre 5865/5875/5890.
        /// </summary>
        internal static string MenuTreeConnectKeyWC5800 {
            get {
                return ResourceManager.GetString("MenuTreeConnectKeyWC5800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochure.
        /// </summary>
        internal static string MenuTreeConnectKeyWC5800Brochure {
            get {
                return ResourceManager.GetString("MenuTreeConnectKeyWC5800Brochure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectMail.
        /// </summary>
        internal static string MenuTreeConnectKeyWC5800DM {
            get {
                return ResourceManager.GetString("MenuTreeConnectKeyWC5800DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string MenuTreeConnectKeyWC5800Flyer {
            get {
                return ResourceManager.GetString("MenuTreeConnectKeyWC5800Flyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectMail.
        /// </summary>
        internal static string MenuTreeDM {
            get {
                return ResourceManager.GetString("MenuTreeDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eConcierge.
        /// </summary>
        internal static string MenuTreeeConcierge {
            get {
                return ResourceManager.GetString("MenuTreeeConcierge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochure.
        /// </summary>
        internal static string MenuTreeeConciergeBrochure {
            get {
                return ResourceManager.GetString("MenuTreeeConciergeBrochure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectMail.
        /// </summary>
        internal static string MenuTreeeConciergeDM {
            get {
                return ResourceManager.GetString("MenuTreeeConciergeDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string MenuTreeeConciergeFlyer {
            get {
                return ResourceManager.GetString("MenuTreeeConciergeFlyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string MenuTreeFlyer {
            get {
                return ResourceManager.GetString("MenuTreeFlyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed Print Services.
        /// </summary>
        internal static string MenuTreeManagedPrintServices {
            get {
                return ResourceManager.GetString("MenuTreeManagedPrintServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochure.
        /// </summary>
        internal static string MenuTreeManagedPrintServicesBrochure {
            get {
                return ResourceManager.GetString("MenuTreeManagedPrintServicesBrochure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectMail.
        /// </summary>
        internal static string MenuTreeManagedPrintServicesDM {
            get {
                return ResourceManager.GetString("MenuTreeManagedPrintServicesDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string MenuTreeManagedPrintServicesFlyer {
            get {
                return ResourceManager.GetString("MenuTreeManagedPrintServicesFlyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multifunction Printer.
        /// </summary>
        internal static string MenuTreeMultifunctionPrinter {
            get {
                return ResourceManager.GetString("MenuTreeMultifunctionPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochure.
        /// </summary>
        internal static string MenuTreeMultifunctionPrinterBrochure {
            get {
                return ResourceManager.GetString("MenuTreeMultifunctionPrinterBrochure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectMail.
        /// </summary>
        internal static string MenuTreeMultifunctionPrinterDM {
            get {
                return ResourceManager.GetString("MenuTreeMultifunctionPrinterDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string MenuTreeMultifunctionPrinterFlyer {
            get {
                return ResourceManager.GetString("MenuTreeMultifunctionPrinterFlyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phaser 4600/4620.
        /// </summary>
        internal static string MenuTreePhaser4600_20 {
            get {
                return ResourceManager.GetString("MenuTreePhaser4600-20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochure.
        /// </summary>
        internal static string MenuTreePhaser4600_20Brochure {
            get {
                return ResourceManager.GetString("MenuTreePhaser4600-20Brochure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectMail.
        /// </summary>
        internal static string MenuTreePhaser4600_20DM {
            get {
                return ResourceManager.GetString("MenuTreePhaser4600-20DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string MenuTreePhaser4600_20Flyer {
            get {
                return ResourceManager.GetString("MenuTreePhaser4600-20Flyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phaser 6010 WC 6015.
        /// </summary>
        internal static string MenuTreePhaser6010WC6015 {
            get {
                return ResourceManager.GetString("MenuTreePhaser6010WC6015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochure.
        /// </summary>
        internal static string MenuTreePhaser6010WC6015Brochure {
            get {
                return ResourceManager.GetString("MenuTreePhaser6010WC6015Brochure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectMail.
        /// </summary>
        internal static string MenuTreePhaser6010WC6015DM {
            get {
                return ResourceManager.GetString("MenuTreePhaser6010WC6015DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string MenuTreePhaser6010WC6015Flyer {
            get {
                return ResourceManager.GetString("MenuTreePhaser6010WC6015Flyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phaser 6500 WC 6505.
        /// </summary>
        internal static string MenuTreePhaser6500WC6505 {
            get {
                return ResourceManager.GetString("MenuTreePhaser6500WC6505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochure.
        /// </summary>
        internal static string MenuTreePhaser6500WC6505Brochure {
            get {
                return ResourceManager.GetString("MenuTreePhaser6500WC6505Brochure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectMail.
        /// </summary>
        internal static string MenuTreePhaser6500WC6505DM {
            get {
                return ResourceManager.GetString("MenuTreePhaser6500WC6505DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string MenuTreePhaser6500WC6505Flyer {
            get {
                return ResourceManager.GetString("MenuTreePhaser6500WC6505Flyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phaser 6600 WC 6605.
        /// </summary>
        internal static string MenuTreePhaser6600WC6605 {
            get {
                return ResourceManager.GetString("MenuTreePhaser6600WC6605", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochure.
        /// </summary>
        internal static string MenuTreePhaser6600WC6605Brochure {
            get {
                return ResourceManager.GetString("MenuTreePhaser6600WC6605Brochure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectMail.
        /// </summary>
        internal static string MenuTreePhaser6600WC6605DM {
            get {
                return ResourceManager.GetString("MenuTreePhaser6600WC6605DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string MenuTreePhaser6600WC6605Flyer {
            get {
                return ResourceManager.GetString("MenuTreePhaser6600WC6605Flyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phaser 6700.
        /// </summary>
        internal static string MenuTreePhaser6700 {
            get {
                return ResourceManager.GetString("MenuTreePhaser6700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochure.
        /// </summary>
        internal static string MenuTreePhaser6700Brochure {
            get {
                return ResourceManager.GetString("MenuTreePhaser6700Brochure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectMail.
        /// </summary>
        internal static string MenuTreePhaser6700DM {
            get {
                return ResourceManager.GetString("MenuTreePhaser6700DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string MenuTreePhaser6700Flyer {
            get {
                return ResourceManager.GetString("MenuTreePhaser6700Flyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phaser 7100.
        /// </summary>
        internal static string MenuTreePhaser7100 {
            get {
                return ResourceManager.GetString("MenuTreePhaser7100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochure.
        /// </summary>
        internal static string MenuTreePhaser7100Brochure {
            get {
                return ResourceManager.GetString("MenuTreePhaser7100Brochure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectMail.
        /// </summary>
        internal static string MenuTreePhaser7100DM {
            get {
                return ResourceManager.GetString("MenuTreePhaser7100DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string MenuTreePhaser7100Flyer {
            get {
                return ResourceManager.GetString("MenuTreePhaser7100Flyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phaser 7800.
        /// </summary>
        internal static string MenuTreePhaser7800 {
            get {
                return ResourceManager.GetString("MenuTreePhaser7800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochure.
        /// </summary>
        internal static string MenuTreePhaser7800Brochure {
            get {
                return ResourceManager.GetString("MenuTreePhaser7800Brochure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectMail.
        /// </summary>
        internal static string MenuTreePhaser7800DM {
            get {
                return ResourceManager.GetString("MenuTreePhaser7800DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string MenuTreePhaser7800Flyer {
            get {
                return ResourceManager.GetString("MenuTreePhaser7800Flyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolidInk.
        /// </summary>
        internal static string MenuTreeSolidInk {
            get {
                return ResourceManager.GetString("MenuTreeSolidInk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brochure.
        /// </summary>
        internal static string MenuTreeSolidInkBrochure {
            get {
                return ResourceManager.GetString("MenuTreeSolidInkBrochure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectMail.
        /// </summary>
        internal static string MenuTreeSolidInkDM {
            get {
                return ResourceManager.GetString("MenuTreeSolidInkDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string MenuTreeSolidInkFlyer {
            get {
                return ResourceManager.GetString("MenuTreeSolidInkFlyer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SolidInk.
        /// </summary>
        internal static string MenuTreeSuppliesOffer
        {
            get
            {
                return ResourceManager.GetString("MenuTreeSolidInk", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DirectMail.
        /// </summary>
        internal static string MenuTreeSuppliesOfferDM
        {
            get
            {
                return ResourceManager.GetString("MenuTreeSuppliesOfferDM", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Flyer.
        /// </summary>
        internal static string MenuTreeSuppliesOfferFlyer
        {
            get
            {
                return ResourceManager.GetString("MenuTreeSuppliesOfferFlyer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No data exists in DB.
        /// </summary>
        internal static string NoDataText {
            get {
                return ResourceManager.GetString("NoDataText", resourceCulture);
            }
        }
    }
}
