//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreatorAdminWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int CountryID { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public string Country1 { get; set; }
        public string ISOCountryCode { get; set; }
        public Nullable<bool> HideInCampaignManager { get; set; }
        public int Region { get; set; }
        public Nullable<int> GeographicRegion { get; set; }
        public Nullable<double> TimeZoneOffset { get; set; }
    }
}
