//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreatorAdminWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomizableArea
    {
        public CustomizableArea()
        {
            this.ImageAreas = new HashSet<ImageArea>();
            this.TextAreas = new HashSet<TextArea>();
        }
    
        public int AreaID { get; set; }
        public int PageID { get; set; }
        public double XPos { get; set; }
        public double YPos { get; set; }
        public double Height { get; set; }
        public double Width { get; set; }
        public double Rotation { get; set; }
        public string Name { get; set; }
    
        public virtual Page Page { get; set; }
        public virtual ICollection<ImageArea> ImageAreas { get; set; }
        public virtual ICollection<TextArea> TextAreas { get; set; }
    }
}
