//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreatorAdminWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.Pages = new HashSet<Page>();
        }
    
        public int DocumentID { get; set; }
        public int TemplateID { get; set; }
        public bool PartnerBranded { get; set; }
        public Nullable<int> ChannelPartnerID { get; set; }
        public string ChannelPartnerLoginID { get; set; }
        public string ChannelPartnerEmail { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int DocumentStateID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> RecycledPaper { get; set; }
        public Nullable<bool> Duplex { get; set; }
        public string PaperOption { get; set; }
        public string PaperSize { get; set; }
        public string CollorCorrection { get; set; }
        public string PrintMode { get; set; }
        public string Attention { get; set; }
        public string CompanyName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string PageSize { get; set; }
        public string TrackingNumber { get; set; }
        public string PartNumber { get; set; }
        public string Carrier { get; set; }
        public string State { get; set; }
        public string ChannelPartnerPhone { get; set; }
        public string Country { get; set; }
        public string CompanyID { get; set; }
    
        public virtual Document Document1 { get; set; }
        public virtual Document Document2 { get; set; }
        public virtual Document Document11 { get; set; }
        public virtual Document Document3 { get; set; }
        public virtual DocumentState DocumentState { get; set; }
        public virtual Template Template { get; set; }
        public virtual Document Document12 { get; set; }
        public virtual Document Document4 { get; set; }
        public virtual DocumentState DocumentState1 { get; set; }
        public virtual ICollection<Page> Pages { get; set; }
    }
}
