//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreatorAdminWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentState
    {
        public DocumentState()
        {
            this.Documents = new HashSet<Document>();
            this.Documents1 = new HashSet<Document>();
        }
    
        public int DocumentStateID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Document> Documents1 { get; set; }
    }
}
