//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreatorAdminWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FontUsage
    {
        public int FontID { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public Nullable<bool> PartnerBranded { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<int> PageID { get; set; }
        public Nullable<int> TextAreaID { get; set; }
    
        public virtual Font Font { get; set; }
    }
}
