//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreatorAdminWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Font
    {
        public int FontID { get; set; }
        public int FontTypeID { get; set; }
        public double Size { get; set; }
        public bool Bold { get; set; }
        public bool Italic { get; set; }
        public bool Underline { get; set; }
        public bool Strikethrough { get; set; }
        public long Color { get; set; }
        public string Name { get; set; }
    
        public virtual FontType FontType { get; set; }
        public virtual FontUsage FontUsage { get; set; }
    }
}
