//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreatorAdminWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FontType
    {
        public FontType()
        {
            this.Fonts = new HashSet<Font>();
        }
    
        public int FontTypeID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Font> Fonts { get; set; }
    }
}
