//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreatorAdminWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.Templates = new HashSet<Template>();
            this.MenuNodeDatas = new HashSet<MenuNodeData>();
            this.MenuNodeDatas1 = new HashSet<MenuNodeData>();
        }
    
        public int LanguageID { get; set; }
        public string LanguageCode { get; set; }
        public string LanguageName { get; set; }
        public string Country { get; set; }
        public Nullable<int> Region { get; set; }
        public Nullable<int> FamilyCodePage { get; set; }
        public Nullable<bool> InUse { get; set; }
    
        public virtual ICollection<Template> Templates { get; set; }
        public virtual ICollection<MenuNodeData> MenuNodeDatas { get; set; }
        public virtual ICollection<MenuNodeData> MenuNodeDatas1 { get; set; }
    }
}
