//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreatorAdminWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageCountry
    {
        public int LanguageID { get; set; }
        public int CountryID { get; set; }
        public string Locale { get; set; }
        public Nullable<int> LocaleID { get; set; }
    }
}
