//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreatorAdminWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.MenuNodeDatas = new HashSet<MenuNodeData>();
        }
    
        public int NodeID { get; set; }
        public int ParentNodeID { get; set; }
        public string NodeName { get; set; }
        public bool IsRoot { get; set; }
        public bool Visible { get; set; }
    
        public virtual ICollection<MenuNodeData> MenuNodeDatas { get; set; }
    }
}
