//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreatorAdminWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuTree
    {
        public MenuTree()
        {
            this.MenuTreeRecursives = new HashSet<MenuTreeRecursive>();
            this.MenuTreeRecursives1 = new HashSet<MenuTreeRecursive>();
            this.Templates = new HashSet<Template>();
            this.Product_MenuTree = new HashSet<Product_MenuTree>();
        }
    
        public int NodeID { get; set; }
        public Nullable<int> ParentNodeID { get; set; }
        public string TranslationKey { get; set; }
        public int LanguageID { get; set; }
        public Nullable<bool> Visible { get; set; }
    
        public virtual ICollection<MenuTreeRecursive> MenuTreeRecursives { get; set; }
        public virtual ICollection<MenuTreeRecursive> MenuTreeRecursives1 { get; set; }
        public virtual ICollection<Template> Templates { get; set; }
        public virtual ICollection<Product_MenuTree> Product_MenuTree { get; set; }
    }
}
