//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreatorAdminWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuTreeRecursive
    {
        public int ParentNodeID { get; set; }
        public int NodeID { get; set; }
        public int Length { get; set; }
    
        public virtual MenuTree MenuTree { get; set; }
        public virtual MenuTree MenuTree1 { get; set; }
    }
}
