//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreatorAdminWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuNodeData
    {
        public int ID { get; set; }
        public int NodeID { get; set; }
        public string MenuText { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public int LanguageID { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Language Language1 { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual Template Template { get; set; }
    }
}
