//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreatorAdminWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public Page()
        {
            this.CustomizableAreas = new HashSet<CustomizableArea>();
        }
    
        public int PageID { get; set; }
        public int PageNumber { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public Nullable<bool> PartnerBranded { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public double Height { get; set; }
        public double Width { get; set; }
        public double Rotation { get; set; }
    
        public virtual ICollection<CustomizableArea> CustomizableAreas { get; set; }
        public virtual Document Document { get; set; }
        public virtual Template Template { get; set; }
    }
}
