//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreatorAdminWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatePartnerBranded
    {
        public int TemplateID { get; set; }
        public bool PartnerBranded { get; set; }
        public string PartNumber { get; set; }
    
        public virtual Template Template { get; set; }
    }
}
