//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreatorAdminWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        public Template()
        {
            this.Documents = new HashSet<Document>();
            this.ExternalCollaterals = new HashSet<ExternalCollateral>();
            this.Pages = new HashSet<Page>();
            this.TemplatePartnerBrandeds = new HashSet<TemplatePartnerBranded>();
            this.MenuTrees = new HashSet<MenuTree>();
            this.MenuNodeDatas = new HashSet<MenuNodeData>();
        }
    
        public int TemplateID { get; set; }
        public int LanguageID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Name { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> RecycledPaper { get; set; }
        public Nullable<bool> Duplex { get; set; }
        public string PaperOption { get; set; }
        public string PaperSize { get; set; }
        public string CollorCorrection { get; set; }
        public string PrintMode { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string Description { get; set; }
        public string PageSize { get; set; }
        public string Detail { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<ExternalCollateral> ExternalCollaterals { get; set; }
        public virtual ICollection<Page> Pages { get; set; }
        public virtual ICollection<TemplatePartnerBranded> TemplatePartnerBrandeds { get; set; }
        public virtual ICollection<MenuTree> MenuTrees { get; set; }
        public virtual Language Language { get; set; }
        public virtual ICollection<MenuNodeData> MenuNodeDatas { get; set; }
    }
}
