//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreatorAdminWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateButton
    {
        public int ID { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public string ChannelPartnerLoginID { get; set; }
        public Nullable<System.DateTime> DateCustomized { get; set; }
        public Nullable<bool> IsCustomized { get; set; }
        public Nullable<bool> IsPartnerBrand { get; set; }
        public Nullable<int> NodeID { get; set; }
    }
}
