//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreatorAdminWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextArea
    {
        public int TextAreaID { get; set; }
        public int AreaID { get; set; }
        public string Text { get; set; }
        public bool FullyEditable { get; set; }
        public int CharsPerLine { get; set; }
        public int Lines { get; set; }
        public string Align { get; set; }
        public Nullable<double> LineSpacing { get; set; }
    
        public virtual CustomizableArea CustomizableArea { get; set; }
    }
}
