//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollateralCreatorAdminWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XeroxCCToolEntities : DbContext
    {
        public XeroxCCToolEntities()
            : base("name=XeroxCCToolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Country> Countries { get; set; }
        public DbSet<CustomizableArea> CustomizableAreas { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<DocumentCarrier> DocumentCarriers { get; set; }
        public DbSet<DocumentState> DocumentStates { get; set; }
        public DbSet<DocumentStateHistory> DocumentStateHistories { get; set; }
        public DbSet<DownloadLog> DownloadLogs { get; set; }
        public DbSet<ExternalCollateral> ExternalCollaterals { get; set; }
        public DbSet<Font> Fonts { get; set; }
        public DbSet<FontType> FontTypes { get; set; }
        public DbSet<FontUsage> FontUsages { get; set; }
        public DbSet<GeneralEnglishText> GeneralEnglishTexts { get; set; }
        public DbSet<GeneralForeignText> GeneralForeignTexts { get; set; }
        public DbSet<ImageArea> ImageAreas { get; set; }
        public DbSet<LanguageCountry> LanguageCountries { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<MenuTree> MenuTrees { get; set; }
        public DbSet<MenuTreeRecursive> MenuTreeRecursives { get; set; }
        public DbSet<Page> Pages { get; set; }
        public DbSet<Product_Family> Product_Family { get; set; }
        public DbSet<Product_MenuTree> Product_MenuTree { get; set; }
        public DbSet<SmartCentreLog> SmartCentreLogs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Template> Templates { get; set; }
        public DbSet<TemplateButton> TemplateButtons { get; set; }
        public DbSet<TemplatePartnerBranded> TemplatePartnerBrandeds { get; set; }
        public DbSet<TextArea> TextAreas { get; set; }
        public DbSet<TranslationGroup> TranslationGroups { get; set; }
        public DbSet<TranslationIDNameSpace> TranslationIDNameSpaces { get; set; }
        public DbSet<TranslationsInTranslationGroup> TranslationsInTranslationGroups { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<MenuNodeData> MenuNodeDatas { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
    }
}
